### ISSUE TITLE
Address CI failure caused by vineyard in mars

### ISSUE THREAD

**Issue by sighingnow** [v6d-io/v6d#1080]
Describe your problem
---------------------

We receive the following bug report from mars:

```
ERROR    mars.services.scheduling.worker.execution:execution.py:129 Failed to run subtask uqezhqbOynqkZuKLAAptQhq1 on band numa-0
Traceback (most recent call last):
  File "/home/runner/miniconda/envs/test/lib/python3.8/site-packages/vineyard/core/resolver.py", line 55, in run
    value = resolver(obj, resolver=self)
  File "/home/runner/miniconda/envs/test/lib/python3.8/site-packages/vineyard/data/dataframe.py", line 110, in pandas_dataframe_resolver
    np_value = resolver.run(obj.member('__values_-value-%d' % idx))
  File "/home/runner/miniconda/envs/test/lib/python3.8/site-packages/vineyard/core/resolver.py", line 59, in run
    raise RuntimeError(  # pylint: disable=raise-missing-from
RuntimeError: Unable to construct the object using resolver: typename is vineyard::Tensor<double>, resolver is <function numpy_ndarray_resolver at 0x7f110ebe8e50>
```

Additional context
------------------

**Comment by sighingnow** [comment]
Addressed by https://github.com/v6d-io/v6d/pull/1078
