### ISSUE TITLE
resolve vineyard::Tensor<std::string> error

### ISSUE THREAD

**Issue by wuyueandrew** [v6d-io/v6d#1312]
Describe your problem
---------------------

consider a string array encoding with user define protocol(not utf8), 
and resolve the elememt of array with arrow large_string could throw exception.
use this cpp programe to create tensor, and use python program to read

cpp code:

```
#include <iostream>
#include <typeinfo>

#include "vineyard/client/client.h"
#include "vineyard/basic/ds/tensor.h"

#include "vineyard/graph/utils/error.h"


int main() {
  vineyard::Client client;
  std::string sock = "/tmp/vineyard.sock";
  VINEYARD_CHECK_OK(client.Connect(sock));

  std::cout << "Connected to IPCServer: " << sock << std::endl;

  std::vector<int64_t> shape{3};
  vineyard::TensorBuilder<std::string> builder = vineyard::TensorBuilder<std::string>(client, shape);

  const char* hexString1 = "\x11\x11\x01\xC0\x0D\x7F";
  std::string str1(hexString1);

  const char* hexString2 = "\x21\x11\x01\xC0\x0D\x7F";
  std::string str2(hexString2);

  const char* hexString3 = "\x11\x11\x01\xC0\x0D\x7F";
  std::string str3(hexString3);

  VINEYARD_CHECK_OK(builder.Append(str1));
  VINEYARD_CHECK_OK(builder.Append(str2));
  VINEYARD_CHECK_OK(builder.Append(str3));

  auto vy_tensor = std::dynamic_pointer_cast<vineyard::Tensor<std::string>>(builder.Seal(client));
  //VY_OK_OR_RAISE(vy_tensor->Persist(client));
  vy_tensor->Persist(client);

  std::cout << "build tensor fin : " << vy_tensor->id() << std::endl;
}
```

python code: 

```
import vineyard
client = vineyard.connect('/tmp/vineyard.sock')
object_id = vineyard.ObjectID('o00228384d4bb82ac')
test = client.get(object_id)
```

bt:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vineyard/core/resolver.py", line 57, in run
    value = resolver(obj)
  File "/usr/local/lib/python3.10/dist-packages/vineyard/data/tensor.py", line 81, in numpy_ndarray_resolver
    return string_array_resolver(obj.member('buffer_')).to_numpy(
  File "pyarrow/array.pxi", line 1475, in pyarrow.lib.Array.to_numpy
  File "pyarrow/error.pxi", line 138, in pyarrow.lib.check_status
 failed.lib.ArrowException: Unknown error: Wrapping �

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/vineyard/core/resolver.py", line 208, in get
    return resolver(obj, __vineyard_client=client, **kw)
  File "/usr/local/lib/python3.10/dist-packages/vineyard/core/resolver.py", line 87, in __call__
    return self.run(obj, **kw)
  File "/usr/local/lib/python3.10/dist-packages/vineyard/core/resolver.py", line 59, in run
    raise RuntimeError(  # pylint: disable=raise-missing-from
RuntimeError: Unable to construct the object using resolver: typename is vineyard::Tensor<std::string>, resolver is <function numpy_ndarray_resolver at 0x7f682757bd00>

**Comment by wuyueandrew** [comment]
```
def string_array_resolver(obj):
    meta = obj.meta
    buffer_data = as_arrow_buffer(obj.member('buffer_data_'))
    buffer_offsets = as_arrow_buffer(obj.member('buffer_offsets_'))
    null_bitmap = as_arrow_buffer(obj.member('null_bitmap_'))
    length = int(meta['length_'])
    null_count = int(meta['null_count_'])
    offset = int(meta['offset_'])
    return pa.lib.Array.from_buffers(
        pa.large_string(),
        length,
        [null_bitmap, buffer_offsets, buffer_data],
        null_count,
        offset,
    )

```
my opinion is, pa.large_string() specify encding of utf8, however std::string dont care encoding. so pa.binary() is a better choose
