### ISSUE TITLE
Metadata inconsistency in sharing numpy array

### ISSUE THREAD

**Issue by qiranq99** [v6d-io/v6d#1987]
Code snippet:

```python
import atexit
import time
import numpy as np
from multiprocessing import Pool
import vineyard
import random
from torch.utils.data import Dataset

class DataLoader:
    def __init__(self, dataset, batch_size=1, shuffle=False, drop_last=False,
                 num_workers=0, prefetch=None, pin_memory=False, timeout=30):
        self.dataset = dataset
        self.batch_size = batch_size
        self.drop_last = drop_last
        self._num_workers = num_workers
        self._prefetch = prefetch
        self._timeout = timeout
        self.pin_memory = pin_memory
        self._client = vineyard.connect()
        self._worker_pool = Pool(
            self._num_workers,
            initializer=_worker_init_fn,
            initargs=(self.dataset, self._client.ipc_socket),
        )
        atexit.register(self.close)

    def __iter__(self):
        return MultiWorkerPool(self._worker_pool, self._prefetch, 
                               self._timeout, self.pin_memory, 
                               self._client, self.dataset)

    def close(self):
        if self._client:
            self._client.clear()
            self._client.memory_trim()
            self._client.close()
        if self._worker_pool:
            self._worker_pool.close()
            self._worker_pool.join()

class MultiWorkerPool:
    def __init__(self, worker_pool, prefetch, timeout, pin_memory, client, dataset):
        self._data_buffer = {}
        self._send_idx = 0
        self._recvd_idx = 0
        self.worker_pool = worker_pool
        self.timeout = timeout
        self.pin_memory = pin_memory
        self.client = client
        self.client.clear()
        self._iter = iter(dataset)
        if prefetch:
            self._prefetch_data(prefetch)
        
    def _prefetch_data(self, count):
        for _ in range(count):
            self._queue_next_data()
        time.sleep(0.0001)  # Allow time for data processing.

    def _queue_next_data(self):
        try:
            data = next(self._iter)
            data_idx = self.worker_pool.apply_async(_worker_fn, (data,))
            self._data_buffer[self._send_idx] = data_idx
            self._send_idx += 1
        except StopIteration:
            pass

    def __next__(self):
        self._queue_next_data()
        if self._recvd_idx == self._send_idx and not self._data_buffer:
            raise StopIteration
        try:
            data = self._get_data_method(self._recvd_idx)
            self._recvd_idx += 1
            return data
        except Exception as e:
            print(f"Error in getting data: {e}")
            self.worker_pool.terminate()
            raise

    def _get_data_method(self, idx):
        data_idx = self._data_buffer.pop(idx)
        oid = data_idx.get(self.timeout)
        data = self.client.get(oid)
        
        if hasattr(self, "_oid_to_del") and self._oid_to_del is not None:
            self.client.delete(self._oid_to_del)
        
        self._oid_to_del = oid
        return data

    def __iter__(self):
        return self

def _worker_init_fn(dataset, socket):
    global g_dataset, g_client
    g_dataset = dataset
    g_client = vineyard.connect(socket).fork()
    print("Initialized on {}".format(socket))

def _worker_fn(idx):
    global g_client
    global g_dataset
    return g_client.put(g_dataset[idx])

class DS(Dataset):
    def __init__(self):
        super().__init__()

    def __getitem__(self, index):
        k = random.randint(64, 128)
        n = random.randint(128, 1024)
        return np.random.rand(k, n, 128)

    def __len__(self):
        return 4096

if __name__ == "__main__":
    ds = DS()
    dl = DataLoader(ds, batch_size=16, prefetch=8, num_workers=8)
    for n_epoch in range(20):
        for i, data in enumerate(dl):
            print(f"Epoch {n_epoch} Batch: {i}, data: {data.shape}")
    dl.close()
    print("Finished")
```

System setup:

-- Ubuntu 22.04
-- python 3.8.10
-- Vineyard 0.21.5
-- Torch 2.0.1

Bug report:

```bash
Error in getting data: Unable to construct the object using resolver: typename is vineyard::Tensor<double>, resolver is <function numpy_ndarray_resolver at 0x11ce3dd30>
Traceback (most recent call last):
  File "/Users/caoye/Desktop/v6d/python/vineyard/core/resolver.py", line 72, in run
    value = resolver(obj)
  File "/Users/caoye/Desktop/v6d/python/vineyard/data/tensor.py", line 126, in numpy_ndarray_resolver
    c_array = np.frombuffer(mem, dtype=value_type).reshape(shape)
ValueError: cannot reshape array of size 3304704 into shape (89,659,128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/caoye/Desktop/v6d/build/test.py", line 123, in <module>
    for i, data in enumerate(dl):
  File "/Users/caoye/Desktop/v6d/build/test.py", line 74, in __next__
    data = self._get_data_method(self._recvd_idx)
  File "/Users/caoye/Desktop/v6d/build/test.py", line 85, in _get_data_method
    data = self.client.get(oid)
  File "/Users/caoye/Desktop/v6d/python/vineyard/core/client.py", line 756, in get
    return get(self, object_id, name, resolver, fetch, **kwargs)
  File "/Users/caoye/Desktop/v6d/python/vineyard/core/resolver.py", line 239, in get
    return resolver(obj, __vineyard_client=client, **kwargs)
  File "/Users/caoye/Desktop/v6d/python/vineyard/core/resolver.py", line 104, in __call__
    return self.run(obj, **kw)
  File "/Users/caoye/Desktop/v6d/python/vineyard/core/resolver.py", line 74, in run
    raise RuntimeError(  # pylint: disable=raise-missing-from
RuntimeError: Unable to construct the object using resolver: typename is vineyard::Tensor<double>, resolver is <function numpy_ndarray_resolver at 0x11ce3dd30>
I20240819 14:14:36.591960 208533763 vineyardd.cc:66] SIGTERM Signal received, stop vineyard server...
```

The error occurs more frequently on resource-constrained machines like PC, but also occurs on server machines randomly.

**Comment by dashanji** [comment]
@qiranq99 Thanks for raising this issue, We'll check it ASAP.

**Comment by dashanji** [comment]
After debugging, we find the different objects are using the same blob. Therefore, we conclude that multiple threads generated the same blob at one time.

```bash
 In [9]: client.get_meta(vineyard.ObjectI
   ...: D("o000017d7074b26d5"))
Out[9]: 
{
    "__timestamp": 1724088724175,
    "buffer_": {
        "id": "o800017d7074a81b8",
        "instance_id": 0,
        "length": 0,
        "nbytes": 0,
        "transient": true,
        "typename": "vineyard::Blob"
    },
    "global": false,
    "id": "o000017d7074b26d5",
    "instance_id": 0,
    "nbytes": 20078592,
    "order_": "\"C\"",
    "partition_index_": "[]",
    "shape_": "[86, 228, 128]",
    "signature": 26212307773112,
    "transient": true,
    "typename": "vineyard::Tensor<double>",
    "value_type_": "float64",
    "value_type_meta_": "<f8"
}

In [10]: client.get_meta(vineyard.Object
    ...: ID("o000017d7074c3ed1"))
Out[10]: 
{
    "__timestamp": 1724088724178,
    "buffer_": {
        "id": "o800017d7074a81b8",
        "instance_id": 0,
        "length": 0,
        "nbytes": 0,
        "transient": true,
        "typename": "vineyard::Blob"
    },
    "global": false,
    "id": "o000017d7074c3ed1",
    "instance_id": 0,
    "nbytes": 72765440,
    "order_": "\"C\"",
    "partition_index_": "[]",
    "shape_": "[110, 646, 128]",
    "signature": 26212307844797,
    "transient": true,
    "typename": "vineyard::Tensor<double>",
    "value_type_": "float64",
    "value_type_meta_": "<f8"
}
```

**Comment by dashanji** [comment]
Hi @qiranq99. Thanks again for your hard work in giving the reproduced code here. It's really an undetectable bug in vineyard.
