### ISSUE TITLE
Vineyard as XCom crashes 

### ISSUE THREAD

**Issue by vlavorini** [v6d-io/v6d#574]
Describe your problem
---------------------
I'm testing Vineyard as XCom backend, whith an ETL that is already tested. The object passed between tasks are Pandas DataFrames and Dict[str, pd.DataFrame].

It starts working fine, XComs are correctly passed between tasks, but at some point I read in the Docker logs:

```
airflow-scheduler_1      | *** Aborted at 1636103786 (unix time) try "date -d @1636103786" if you are using GNU date ***
airflow-scheduler_1      | PC: @                0x0 (unknown)
airflow-scheduler_1      | *** SIGBUS (@0x7fd2841cc628) received by PID 22 (TID 0x7fd2977fe700) from PID 18446744071631062568; stack trace: ***
airflow-scheduler_1      |     @     0x7fd2cf3b3730 (unknown)
airflow-scheduler_1      |     @           0xc246d0 dlmalloc
airflow-scheduler_1      |     @           0xc251ed (unknown)
airflow-scheduler_1      |     @           0xc21c7f vineyard::BulkAllocator::Memalign()
airflow-scheduler_1      |     @           0xc25bd4 vineyard::BulkStore::AllocateMemory()
airflow-scheduler_1      |     @           0xc26497 vineyard::BulkStore::Create()
airflow-scheduler_1      |     @           0xc18000 vineyard::SocketConnection::doCreateBuffer()
airflow-scheduler_1      |     @           0xc1a1d2 vineyard::SocketConnection::processMessage()
airflow-scheduler_1      |     @           0xc1a710 (unknown)
airflow-scheduler_1      |     @           0xc1a7ed (unknown)
airflow-scheduler_1      |     @           0xc05979 boost::asio::detail::scheduler::do_run_one()
airflow-scheduler_1      |     @           0xc05b43 boost::asio::detail::scheduler::run()
airflow-scheduler_1      |     @           0xc3670f boost::asio::io_context::run()
airflow-scheduler_1      |     @          0x14a253f (unknown)
airflow-scheduler_1      |     @     0x7fd2cf3a8fa3 start_thread
airflow-scheduler_1      |     @     0x7fd2cf1544cf clone
```

While in the task logs:

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1458, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1517, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2262, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/contrib/airflow/xcom/backend.py", line 87, in set
    value = VineyardXCom.serialize_value(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/contrib/airflow/xcom/backend.py", line 161, in serialize_value
    value_id = client.put(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/core/builder.py", line 153, in put
    meta = get_current_builders().run(client, value, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/core/builder.py", line 74, in run
    return self.__factory[ty](client, value, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/data/dataframe.py", line 45, in pandas_dataframe_builder
    meta.add_member('index_', builder.run(client, value.index))
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/core/builder.py", line 74, in run
    return self.__factory[ty](client, value, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/data/index.py", line 32, in pandas_index_builder
    meta.add_member('value_', builder.run(client, value.to_numpy(), **kw))
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/core/builder.py", line 74, in run
    return self.__factory[ty](client, value, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/data/tensor.py", line 58, in numpy_ndarray_builder
    meta.add_member('buffer_', build_numpy_buffer(client, value))
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/data/utils.py", line 89, in build_numpy_buffer
    return build_buffer(client, address, array.nbytes)
  File "/home/airflow/.local/lib/python3.7/site-packages/vineyard/data/utils.py", line 79, in build_buffer
    buffer = client.create_blob(size)
vineyard._C.IOErrorException: IOError: Receive message failed: encountered unexpected EOF
```
Tested with and without XCom pickling, same issue.
----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version: 

Airflow 2.2 on its official docker-composed project. LocalExecutor (no Celery)

**Comment by sighingnow** [comment]
When running vineyard inside the docker container, you need to specify a `--shm-size` options to `docker run` (the default value is 64Mi), the value means how much shared memory that processes inside the docker container can use.

**Comment by vlavorini** [comment]
I confirm this solves my issue.
As reference, this is the relevant section in the docker-compose file:

```
  airflow-scheduler:
    <<: *airflow-common
    command: bash /sched_n_vineyard.sh
    shm_size: 2gb
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      airflow-webserver:
        "condition": service_healthy
````

**Comment by sighingnow** [comment]
Thanks for the quick response!

**Comment by ogremagi4** [comment]
Hi, im running it on monolith (no docker) and facing the same issue.

Vineyard is run on supervisor:

`python3 -m vineyard --socket=/tmp/vineyard.sock --size=90G`

and the only difference in error traceback is that im getting SIGSEV (op had SIGBUS)

`*** SIGSEGV (@0x9) received by PID 13757 (TID 0x7f96f6fdd700) from PID 9; stack trace: ***`

**Comment by sighingnow** [comment]
Looks strange. May I you which version of vineyard and what system you are using to run vineyard?

It would be great if I could have some way to reproduce the failure.

Thanks!

**Comment by ogremagi4** [comment]
Thanks for such a quick response!
im using 

Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

Python 3.9.2 
Airflow verison 2.3.4

not sure how to reproduce the issue. i think it'd be just enough to run etls and cleanup xcoms like i do:

```
@provide_session
def cleanup_xcom(context, session=None):
    for task_instance in context['dag'].tasks:
        XCom.clear(
            task_id = task_instance.task_id, 
            dag_id = task_instance.dag_id, 
            execution_date = context['execution_date'])

default_dag_kwargs = dict(
    catchup=False, 
    max_active_runs=1,
    on_success_callback = cleanup_xcom,
    on_failure_callback = cleanup_xcom
)
```

**Comment by sighingnow** [comment]
May I known which version of vineyard are you working with? The vineyard version can be retrieved by

```bash
python3 -c "import vineyard; print(vineyard.__version__)"
```

> `*** SIGSEGV (@0x9) received by PID 13757 (TID 0x7f96f6fdd700) from PID 9; stack trace: ***`

Was there any stack trace been printed out?

**Comment by ogremagi4** [comment]
vineyard version is '0.7.2'

```
declare -x HOME="/home/airflow"
declare -x INVOCATION_ID="443c231a212a44c18d6267c0a0aea967"
declare -x JOURNAL_STREAM="9:16520"
declare -x LANG="C.UTF-8"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/home/airflow/airflow"
declare -x PYTHONPATH="/home/airflow/airflow"
declare -x SHLVL="1"
declare -x SUPERVISOR_ENABLED="1"
declare -x SUPERVISOR_GROUP_NAME="vineyard"
declare -x SUPERVISOR_PROCESS_NAME="vineyard"
declare -x SUPERVISOR_SERVER_URL="unix:///tmp/supervisor.sock"
declare -x USER="airflow"
I20221123 07:04:42.157685 13757 vineyardd.cc:91] Hello vineyard v0.7.2!
I20221123 07:04:42.158448 13757 meta_service.h:94] meta service is starting ...
I20221123 07:04:42.189771 13757 allocator.cc:60] shmax: 60513193984
W20221123 07:04:42.189803 13757 allocator.cc:62] The 'size' is greater than the maximum shared memory size (60513193984)
W20221123 07:04:42.190001 13757 allocator.cc:65]     If you are inside a Docker container, please pass the argument '--shm-size' when 'docker run'.
I20221123 07:04:42.190198 13757 usage.h:476] No spill path set, disable spill...
I20221123 07:04:42.200986 13757 meta_service.h:818] Instance join: 8
I20221123 07:04:42.201056 13757 etcd_meta_service.cc:320] start background etcd watch, since 13507
I20221123 07:04:42.230145 13757 meta_service.h:416] Decide to set rank as 9
I20221123 07:04:42.230183 13757 meta_service.h:818] Instance join: 9
I20221123 07:04:42.241645 13757 meta_service.h:818] Instance join: 9
I20221123 07:04:42.242815 13757 ipc_server.cc:54] Vineyard will listen on "/tmp/vineyard.sock" for IPC
I20221123 07:04:42.242854 13757 rpc_server.cc:54] Vineyard will listen on 0.0.0.0:9600 for RPC
E20221123 07:04:42.600126 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee46cc9130c0
E20221123 07:04:42.619650 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee4b52c9836e
E20221123 07:04:42.631477 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee55e2133092
E20221123 07:04:42.636564 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee5be3d5f63e
E20221123 07:04:42.652405 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee4ffa47ecda
E20221123 07:04:42.680668 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee5190ab4ec8
E20221123 07:04:45.197922 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee51f3c04c16
E20221123 07:04:45.224015 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee491f9fa704
E20221123 07:04:45.228746 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee4922fb764e
E20221123 07:04:51.334249 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee24fa8b9e10
E20221123 07:04:51.340684 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee244dae3d56
E20221123 07:04:51.344465 13757 socket_server.cc:746] Object not exists: failed to delete: Metatree subtree not exists.: delete subtree failed: o0003ee1ef945617c
E20221123 07:08:42.284135 13757 meta_service.h:498] Instance 8 timeout
I20221123 07:08:42.288496 13757 meta_service.h:821] Instance exit: 8
I20221123 07:08:42.289875 13757 meta_service.h:821] Instance exit: 8
*** Aborted at 1669196415 (unix time) try "date -d @1669196415" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x9) received by PID 13757 (TID 0x7f96f6fdd700) from PID 9; stack trace: ***
    @     0x7f9718f0c730 (unknown)
    @          0x18b13e7 std::__detail::_List_node_base::_M_unhook()
    @           0xd5195e vineyard::detail::ColdObjectTracker<>::LRU::Unref()
    @           0xd51ce4 vineyard::detail::ColdObjectTracker<>::AddDependency()
    @           0xd51dd0 vineyard::detail::ColdObjectTracker<>::AddDependency()
    @           0xd454ed vineyard::SocketConnection::doGetBuffers()
    @           0xd4918b vineyard::SocketConnection::processMessage()
    @           0xd497dd (unknown)
    @           0xd498ba (unknown)
    @           0xd2e1db boost::asio::detail::scheduler::do_run_one()
    @           0xd2e3a5 boost::asio::detail::scheduler::run()
    @           0xd674eb boost::asio::io_context::run()
    @          0x18b662f (unknown)
    @     0x7f9718f01fa3 start_thread
    @     0x7f9718cb006f clone
```

**Comment by sighingnow** [comment]
It was a fixed issue and you could try upgrade your vineyard installation with

```
pip3 install -U vineyard airflow-provider-vineyard
```

and try again.
