### ISSUE TITLE
Vineyard as XCom backend: issue w serialization?

### ISSUE THREAD

**Issue by vlavorini** [v6d-io/v6d#575]
Describe your problem
---------------------

On Airflow, switching a DAG to Vineyard XCom I got an error bout data types:

```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1422, in _execute_task_with_callbacks
    RenderedTaskInstanceFields.write(RenderedTaskInstanceFields(ti=self, render_templates=False))
  File "<string>", line 4, in __init__
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/renderedtifields.py", line 58, in __init__
    field: serialize_template_field(getattr(self.task, field)) for field in self.task.template_fields
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/renderedtifields.py", line 58, in <dictcomp>
    field: serialize_template_field(getattr(self.task, field)) for field in self.task.template_fields
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/serialization/helpers.py", line 41, in serialize_template_field
    return str(template_field)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 1002, in __repr__
    show_dimensions=show_dimensions,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 1129, in to_string
    decimal=decimal,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 533, in __init__
    self.truncate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 722, in truncate
    self._truncate_vertically()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 762, in _truncate_vertically
    self.tr_frame = concat((head, tail))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 307, in concat
    return op.get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 533, in get_result
    mgrs_indexers, self.new_axes, concat_axis=self.bm_axis, copy=self.copy
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/concat.py", line 230, in concatenate_managers
    b = blk.make_block_same_class(values, placement=placement)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 274, in make_block_same_class
    return type(self)(values, placement=placement, ndim=self.ndim)
TypeError: Argument 'values' has incorrect type (expected numpy.ndarray, got DatetimeArray)
```

**Comment by sighingnow** [comment]
I can confirm that this is a bug, as the `datetime` type has been tested yet.

**Comment by sighingnow** [comment]
Will be fixed ASAP.

**Comment by vlavorini** [comment]
can you also please update the package in pip? Thank you so much for all the effort!

**Comment by sighingnow** [comment]
> can you also please update the package in pip? Thank you so much for all the effort!

I will cut a new release before this Friday.

**Comment by sighingnow** [comment]
> > can you also please update the package in pip? Thank you so much for all the effort!
> 
> I will cut a new release before this Friday.

v0.3.7 has been uploaded to pypi. Thanks for your patience!
