### ISSUE TITLE
Vineyard - Airflow Celery Executor: Can Not Transfer Dataframe Between Tasks

### ISSUE THREAD

**Issue by canersnli** [v6d-io/v6d#652]
Describe your problem
---------------------

A clear and concise description of what your problem is. It might be a bug,
a feature request, or just a problem that need support from the vineyard team.

----------------------------------------------------------------------

If is is a **bug report**, to help us reproducing this bug, please provide information below:

1. Your Operation System version (`uname -a`):  
    - Master:   Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)
    - Worker 1 & 2: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-89-generic x86_64)
2. The version of vineyard you use (`vineyard.__version__`):  0.3.16
3. Versions of crucial packages, such as gcc, numpy, pandas, etc.: 
     pandas=1.3.1  numpy=1.21.1   airflow=2.1.0  gcc=(Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
4. Full stack of the error (if there are a crash): 

*** Log file does not exist: /data/airflow/logs/taskflow_etl_pandas/extract/2022-01-25T11:54:00.395325+00:00/1.log
*** Fetching from: http://DTEKAIRFLOWWP1.fw.dteknoloji.com.tr:8793/log/taskflow_etl_pandas/extract/2022-01-25T11:54:00.395325+00:00/1.log

[2022-01-25 14:54:01,671] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: taskflow_etl_pandas.extract 2022-01-25T11:54:00.395325+00:00 [queued]>
[2022-01-25 14:54:01,690] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: taskflow_etl_pandas.extract 2022-01-25T11:54:00.395325+00:00 [queued]>
[2022-01-25 14:54:01,690] {taskinstance.py:1067} INFO - 
[2022-01-25 14:54:01,690] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-01-25 14:54:01,690] {taskinstance.py:1069} INFO - 
[2022-01-25 14:54:01,699] {taskinstance.py:1087} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2022-01-25T11:54:00.395325+00:00
[2022-01-25 14:54:01,704] {standard_task_runner.py:52} INFO - Started process 2502514 to run task
[2022-01-25 14:54:01,709] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'taskflow_etl_pandas', 'extract', '2022-01-25T11:54:00.395325+00:00', '--job-id', '225', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_df_transfer_between_tasks.py', '--cfg-path', '/tmp/tmpk31jbrbm', '--error-file', '/tmp/tmpi098c023']
[2022-01-25 14:54:01,710] {standard_task_runner.py:77} INFO - Job 225: Subtask extract
[2022-01-25 14:54:01,783] {logging_mixin.py:104} INFO - Running <TaskInstance: taskflow_etl_pandas.extract 2022-01-25T11:54:00.395325+00:00 [running]> on host DTEKAIRFLOWWP1.fw.dteknoloji.com.tr
[2022-01-25 14:54:01,868] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=taskflow_etl_pandas
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-01-25T11:54:00.395325+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-25T11:54:00.395325+00:00
[2022-01-25 14:54:01,875] {python.py:151} INFO - Done. Returned value was: ['a', 'b']
[2022-01-25 14:54:01,875] {xcom.py:228} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2022-01-25 14:54:01,876] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1344, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1919, in xcom_push
    XCom.set(
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/xcom.py", line 79, in set
    value = XCom.serialize_value(value)
  File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/xcom.py", line 226, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/data/anaconda3/envs/airflow/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/data/anaconda3/envs/airflow/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/data/anaconda3/envs/airflow/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/data/anaconda3/envs/airflow/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2022-01-25 14:54:01,877] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=taskflow_etl_pandas, task_id=extract, execution_date=20220125T115400, start_date=20220125T115401, end_date=20220125T115401
[2022-01-25 14:54:01,918] {local_task_job.py:151} INFO - Task exited with return code 1

5. Minimized code to reproduce the error:

```
import numpy as np
import pandas as pd

from airflow.decorators import dag, task
from airflow.utils.dates import days_ago

default_args = {
    'owner': 'airflow',
}

@dag(default_args=default_args, schedule_interval=None, start_date=days_ago(2), tags=['example'])
def taskflow_etl_pandas():
    @task()
    def extract():
        df = pd.DataFrame({
            'a': np.random.rand(100000),
            'b': np.random.rand(100000),
        })
        return df

    @task(multiple_outputs=True)
    def transform(dataframe):
        return {"total_order_value": dataframe["a"].sum()}

    @task()
    def load(total_order_value: float):
        print(f"Total order value is: {total_order_value:.2f}")

    order_data = extract()
    order_summary = transform(order_data)
    load(order_summary["total_order_value"])

taskflow_etl_pandas_dag = taskflow_etl_pandas()
```

Hello, I am trying to integrate vineyard backend on airflow cluster, however it seems like airflow still uses default xcom backend as seen on error; 
   File "/data/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/xcom.py", line 226, in serialize_value

I will explain steps I did to configure backend of my cluster. 

1) Installed vineyard on all three nodes on airflow environment:  pip install airflow-provider-vineyard
2) Added last 2 lines to my airflow.env file which is in /data/aiflow/ folder. There are  4 env variables in  airflow.env file now. Did same on all 3 nodes.

AIRFLOW_CONFIG=/data/airflow/airflow.cfg
AIRFLOW_HOME=/data/airflow
AIRFLOW__CORE__XCOM_BACKEND=vineyard.contrib.airflow.xcom.VineyardXCom
AIRFLOW__VINEYARD__IPC_SOCKET=/tmp/vineyard.sock

3) Launched vineyard server on all nodes: nohup python -m vineyard --socket=/tmp/vineyard.sock 
Checked that 2379, 2380 and 6900 vineyard ports are being listened and every single node has telnet connection to these ports on other 2 nodes. 

4) Restarted webserver and scheduler services on master node.
    systemctl restart airflow-webserver
    systemctl restart airflow-scheduler

After I got fail on airflow task with these default settings, I tried some other configurations:

I found out that, at step 2,  vineyard.contrib.airflow.xcom.VineyardXCom path seems missing backend.py between xcom folder and VineYardXCom class so I changed this line to AIRFLOW__CORE__XCOM_BACKEND=vineyard.contrib.airflow.xcom.backend.VineyardXCom
<img width="1010" alt="xcom ss" src="https://user-images.githubusercontent.com/70806315/150982102-b061c59b-71cf-42e1-9c28-46380d7c9fd8.png">

Later I added deployement setting to disitributed on launching command: 
nohup python -m vineyard --socket=/tmp/vineyard.sock --deployment=distributed

Finally, I have changed xcom_backend setting pointing to VineyardXCom class on airflow.cfg file.

'#Path to custom XCom class that will be used to store and resolve operators results
"#Example: xcom_backend = path.to.CustomXCom
"#xcom_backend = airflow.models.xcom.BaseXCom'
xcom_backend = vineyard.contrib.airflow.xcom.backend.VineyardXCom

After each change, I re-launched vineyard server on all nodes and restarted airflow webserver and scheduler, however None of trials succeeded on airflow. still getting same error I shared at top.  Looking forward for your help. Thanks in advance.

**Comment by sighingnow** [comment]
Seems that the vineyard backend doesn't take into affect.

I'm sure if it is a regression bug that related to airflow's version. I will try to reproduce with airflow `2.1.0`.

**Comment by canersnli** [comment]
Thanks for quick response. If you dont see any incorrect or missing step on my configuration steps then it is highly likely related to airflow version. Because I also tried to set custom s3 backend and having exactly same error as I am trying to transfer dataframe between tasks. S3 Backend does not take into affect aswell. 

Which airflow version do you suggest for me, latest one? Maybe I can upgrade airflow.

**Comment by canersnli** [comment]
I wanted to share quick update. After I had upgraded airflow from 2.1.0 to 2.2.3, I could have activated vineyard backend. However, socket connection error has occured now. I checked vineyard services, all of them are up and running. Any advice ?


```

Log file does not exist: /data/airflow/logs/tutorial_taskflow_api_etl/extract/2022-01-31T19:55:58.987530+00:00/1.log
Fetching from: http://DTEKAIRFLOWWP1.fw.dteknoloji.com.tr:8793/log/tutorial_taskflow_api_etl/extract/2022-01-31T19:55:58.987530+00:00/1.log

[2022-01-31, 22:56:00 UTC] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl.extract manual__2022-01-31T19:55:58.987530+00:00 [queued]>
[2022-01-31, 22:56:00 UTC] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial_taskflow_api_etl.extract manual__2022-01-31T19:55:58.987530+00:00 [queued]>
[2022-01-31, 22:56:00 UTC] {taskinstance.py:1238} INFO - 

[2022-01-31, 22:56:00 UTC] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-31, 22:56:00 UTC] {taskinstance.py:1240} INFO - 

[2022-01-31, 22:56:00 UTC] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2022-01-31 19:55:58.987530+00:00
[2022-01-31, 22:56:00 UTC] {standard_task_runner.py:52} INFO - Started process 3266293 to run task
[2022-01-31, 22:56:00 UTC] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'tutorial_taskflow_api_etl', 'extract', 'manual__2022-01-31T19:55:58.987530+00:00', '--job-id', '473', '--raw', '--subdir', '/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/example_dags/tutorial_taskflow_api_etl.py', '--cfg-path', '/tmp/tmp47kohjns', '--error-file', '/tmp/tmp37ckf_hd']
[2022-01-31, 22:56:00 UTC] {standard_task_runner.py:77} INFO - Job 473: Subtask extract
[2022-01-31, 22:56:00 UTC] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial_taskflow_api_etl.extract manual__2022-01-31T19:55:58.987530+00:00 [running]> on host DTEKAIRFLOWWP1.fw.dteknoloji.com.tr
[2022-01-31, 22:56:00 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/vineyard/contrib/airflow/xcom/backend.py:147: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  for result in query.with_entities(VineyardXCom.value):

[2022-01-31, 22:56:00 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/vineyard/contrib/airflow/xcom/backend.py:156: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  query.delete()

[2022-01-31, 22:56:00 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/renderedtifields.py:126: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  session.merge(self)

[2022-01-31, 22:56:00 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/renderedtifields.py:197: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
  tuple_(cls.dag_id, cls.task_id, cls.execution_date).notin_(subq2),

[2022-01-31, 22:56:00 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/renderedtifields.py:194: SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  session.query(cls).filter(

[2022-01-31, 22:56:00 UTC] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=tutorial_taskflow_api_etl
AIRFLOW_CTX_TASK_ID=extract
AIRFLOW_CTX_EXECUTION_DATE=2022-01-31T19:55:58.987530+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-31T19:55:58.987530+00:00
[2022-01-31, 22:56:00 UTC] {python.py:175} INFO - Done. Returned value was: {'1001': 301.27, '1002': 433.21, '1003': 502.22}
[2022-01-31, 22:56:10 UTC] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2135, in xcom_push
    XCom.set(
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/vineyard/contrib/airflow/xcom/backend.py", line 87, in set
    value = VineyardXCom.serialize_value(value)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/vineyard/contrib/airflow/xcom/backend.py", line 160, in serialize_value
    client = vineyard.connect(VineyardXCom.options()['ipc_socket'])
vineyard._C.ConnectionFailedException: Connection failed: Failed to connect to vineyardd: 
[2022-01-31, 22:56:10 UTC] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=tutorial_taskflow_api_etl, task_id=extract, execution_date=20220131T195558, start_date=20220131T195600, end_date=20220131T195610
[2022-01-31, 22:56:10 UTC] {standard_task_runner.py:89} ERROR - Failed to execute job 473 for task extract
Traceback (most recent call last):
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1514, in _execute_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2135, in xcom_push
    XCom.set(
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/utils/session.py", line 67, in wrapper
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/vineyard/contrib/airflow/xcom/backend.py", line 87, in set
    value = VineyardXCom.serialize_value(value)
  File "/data/anaconda3/envs/airflow2/lib/python3.9/site-packages/vineyard/contrib/airflow/xcom/backend.py", line 160, in serialize_value
    client = vineyard.connect(VineyardXCom.options()['ipc_socket'])
vineyard._C.ConnectionFailedException: Connection failed: Failed to connect to vineyardd: 
[2022-01-31, 22:56:10 UTC] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-31, 22:56:10 UTC] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-31, 22:56:10 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/dag.py:1076: SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)

[2022-01-31, 22:56:10 UTC] {warnings.py:109} WARNING - /data/anaconda3/envs/airflow2/lib/python3.9/site-packages/airflow/models/dag.py:1076: SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
  return qry.value(DagModel.is_paused)
```

**Comment by sighingnow** [comment]
> 

You need to start vineyard daemon (on airflow workers) before executing airflow tasks.

See also https://github.com/v6d-io/v6d/blob/main/python/vineyard/contrib/airflow/README.md

> 2. Configure Vineyard locally
>
> The vineyard server can be easier launched locally with the following command:
>
> ```bash
> python3 -m vineyard --socket=/tmp/vineyard.sock

>

**Comment by sighingnow** [comment]
Close as addressed.
